-- Public input validation and privacy-preserving rate limiting.
--
-- Non-destructive. Existing rows are preserved. Rate-limit identifiers are
-- stored as hashes only; raw emails, phones, locations, and IPs are not written
-- to the rate_limit_events table.

create extension if not exists pgcrypto;

create table if not exists public.rate_limit_events (
  id bigint generated by default as identity primary key,
  action text not null,
  identifier_hash text not null,
  created_at timestamptz not null default now()
);

create index if not exists rate_limit_events_action_hash_created_idx
  on public.rate_limit_events (action, identifier_hash, created_at desc);

alter table public.rate_limit_events enable row level security;
revoke all on public.rate_limit_events from anon, authenticated;

create or replace function public.normalized_rate_limit_identifier(
  p_identifier text
)
returns text
language sql
stable
security definer
set search_path = public
as $$
  select encode(
    extensions.digest(
      'mkc-rate-limit-v1:' || lower(trim(coalesce(p_identifier, 'anonymous'))),
      'sha256'
    ),
    'hex'
  )
$$;

create or replace function public.assert_rate_limit(
  p_action text,
  p_identifier text,
  p_hour_limit integer,
  p_day_limit integer
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_hash text;
  v_hour_count integer;
  v_day_count integer;
begin
  if coalesce(p_action, '') = '' then
    raise exception 'Rate-limit action is required' using errcode = '22023';
  end if;

  v_hash := public.normalized_rate_limit_identifier(p_identifier);

  select count(*) into v_hour_count
  from public.rate_limit_events
  where action = p_action
    and identifier_hash = v_hash
    and created_at > now() - interval '1 hour';

  if v_hour_count >= p_hour_limit then
    raise exception 'Too many attempts. Please wait and try again later.' using errcode = 'P0001';
  end if;

  select count(*) into v_day_count
  from public.rate_limit_events
  where action = p_action
    and identifier_hash = v_hash
    and created_at > now() - interval '1 day';

  if v_day_count >= p_day_limit then
    raise exception 'Daily limit reached. Please try again later.' using errcode = 'P0001';
  end if;

  insert into public.rate_limit_events (action, identifier_hash)
  values (p_action, v_hash);
end;
$$;

create or replace function public.prune_rate_limit_events(
  p_before timestamptz default now() - interval '30 days'
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_deleted integer;
begin
  if not public.is_admin() then
    raise exception 'Admin role required' using errcode = '42501';
  end if;

  delete from public.rate_limit_events
  where created_at < p_before;

  get diagnostics v_deleted = row_count;
  return v_deleted;
end;
$$;

create or replace function public.validate_public_report_submission()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_identifier text;
begin
  new.tracking_code := upper(trim(coalesce(new.tracking_code, '')));
  new.issue_type := left(trim(coalesce(new.issue_type, '')), 120);
  new.location_name := left(trim(coalesce(new.location_name, '')), 240);
  new.area := left(trim(coalesce(new.area, new.location_name, '')), 240);
  new.description := left(trim(coalesce(new.description, '')), 2000);
  new.urgency := left(trim(coalesce(new.urgency, 'Medium')), 40);
  new.reporter_type := left(trim(coalesce(new.reporter_type, 'Public Reporter')), 80);
  new.reporter_name := left(trim(coalesce(new.reporter_name, '')), 120);
  new.reporter_phone := left(trim(coalesce(new.reporter_phone, '')), 60);
  new.reporter_email := left(lower(trim(coalesce(new.reporter_email, ''))), 160);
  new.near_sensitive_area := case when new.near_sensitive_area = 'Yes' then 'Yes' else 'No' end;
  new.status := coalesce(nullif(new.status, ''), 'Reported');

  if new.status <> 'Reported' then
    raise exception 'Public reports must start as Reported' using errcode = '23514';
  end if;

  if new.tracking_code !~ '^MKC-[0-9]{4}-[A-Z0-9]+$' then
    raise exception 'Invalid tracking code' using errcode = '23514';
  end if;

  if length(new.issue_type) < 3 then
    raise exception 'Issue type is required' using errcode = '23514';
  end if;

  if length(new.location_name) < 3 then
    raise exception 'Location is required' using errcode = '23514';
  end if;

  if length(new.description) < 10 then
    raise exception 'Description must be at least 10 characters' using errcode = '23514';
  end if;

  if new.latitude is null or new.longitude is null then
    raise exception 'Latitude and longitude are required' using errcode = '23514';
  end if;

  if new.latitude < -5 or new.latitude > 5 or new.longitude < 33 or new.longitude > 42 then
    raise exception 'Report location must be within Kenya' using errcode = '23514';
  end if;

  v_identifier := coalesce(
    nullif(new.reporter_email, ''),
    nullif(new.reporter_phone, ''),
    new.location_name || ':' || date_trunc('hour', now())::text
  );

  perform public.assert_rate_limit(
    'public_report',
    v_identifier,
    6,
    20
  );

  return new;
end;
$$;

drop trigger if exists validate_public_report_submission on public.reports;
create trigger validate_public_report_submission
before insert on public.reports
for each row
execute function public.validate_public_report_submission();

create or replace function public.validate_access_request_submission()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  new.full_name := left(trim(coalesce(new.full_name, '')), 160);
  new.email := left(lower(trim(coalesce(new.email, ''))), 160);
  new.phone := left(trim(coalesce(new.phone, '')), 60);
  new.requested_role := trim(coalesce(new.requested_role, ''));
  new.area := left(trim(coalesce(new.area, '')), 160);
  new.organization_name := left(trim(coalesce(new.organization_name, '')), 180);
  new.reason := left(trim(coalesce(new.reason, '')), 2000);
  new.status := coalesce(nullif(new.status, ''), 'Pending');

  if length(new.full_name) < 2 then
    raise exception 'Full name is required' using errcode = '23514';
  end if;

  if new.email !~* '^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$' then
    raise exception 'A valid email is required' using errcode = '23514';
  end if;

  if new.requested_role not in ('champion', 'organization') then
    raise exception 'Invalid requested role' using errcode = '23514';
  end if;

  if new.requested_role = 'organization' and length(new.organization_name) < 2 then
    raise exception 'Organization name is required' using errcode = '23514';
  end if;

  if length(new.reason) < 10 then
    raise exception 'Reason must be at least 10 characters' using errcode = '23514';
  end if;

  if new.status <> 'Pending' then
    raise exception 'Access requests must start as Pending' using errcode = '23514';
  end if;

  perform public.assert_rate_limit(
    'access_request',
    new.email,
    3,
    5
  );

  return new;
end;
$$;

drop trigger if exists validate_access_request_submission on public.access_requests;
create trigger validate_access_request_submission
before insert on public.access_requests
for each row
execute function public.validate_access_request_submission();

create or replace function public.submit_community_confirmation(
  p_tracking_code text,
  p_confirmation text,
  p_note text default ''
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_report public.reports%rowtype;
  v_confirmation public.community_confirmations%rowtype;
  v_note text;
begin
  select * into v_report
  from public.reports
  where tracking_code = upper(trim(p_tracking_code));

  if not found then
    raise exception 'Report not found' using errcode = 'P0002';
  end if;

  if v_report.status <> 'Resolved' then
    raise exception 'Community confirmation is only available for resolved reports' using errcode = 'P0001';
  end if;

  if p_confirmation not in ('Confirmed', 'Disputed') then
    raise exception 'Invalid confirmation value' using errcode = '22023';
  end if;

  v_note := left(trim(coalesce(p_note, '')), 500);

  perform public.assert_rate_limit(
    'community_confirmation',
    upper(trim(p_tracking_code)),
    4,
    10
  );

  if exists (
    select 1
    from public.community_confirmations
    where report_id = v_report.id
      and review_status = 'Pending'
  ) then
    raise exception 'Community feedback is already pending review' using errcode = 'P0001';
  end if;

  insert into public.community_confirmations (
    report_id,
    tracking_code,
    confirmation,
    note,
    review_status
  )
  values (
    v_report.id,
    v_report.tracking_code,
    p_confirmation,
    v_note,
    'Pending'
  )
  returning * into v_confirmation;

  insert into public.report_updates (
    report_id,
    status,
    note,
    updated_by_name
  )
  values (
    v_report.id,
    'Community Feedback Submitted',
    coalesce(nullif(v_note, ''), case when p_confirmation = 'Confirmed' then 'Community confirmed the issue appears resolved.' else 'Community disputed the resolution.' end),
    'Community Feedback'
  );

  return jsonb_build_object(
    'success', true,
    'confirmation_id', v_confirmation.id,
    'report_id', v_report.id,
    'status', 'Pending'
  );
end;
$$;

revoke execute on function public.normalized_rate_limit_identifier(text) from public, anon, authenticated;
revoke execute on function public.assert_rate_limit(text, text, integer, integer) from public, anon, authenticated;
revoke execute on function public.prune_rate_limit_events(timestamptz) from public, anon;
grant execute on function public.prune_rate_limit_events(timestamptz) to authenticated;
revoke execute on function public.validate_public_report_submission() from public, anon, authenticated;
revoke execute on function public.validate_access_request_submission() from public, anon, authenticated;
revoke execute on function public.submit_community_confirmation(text, text, text) from public;
grant execute on function public.submit_community_confirmation(text, text, text) to anon, authenticated;
