-- Make Kenya Clean staff access hardening.
--
-- This migration is intentionally conservative for an existing live Supabase
-- project. It does not drop tables, truncate data, rewrite primary keys, or
-- force column type conversions. If an existing column has a different type,
-- PostgreSQL will keep it as-is and these ADD COLUMN IF NOT EXISTS statements
-- will not alter it.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default '',
  role text not null default 'pending',
  area text not null default '',
  organization_name text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles add column if not exists full_name text not null default '';
alter table public.profiles add column if not exists role text not null default 'pending';
alter table public.profiles add column if not exists area text not null default '';
alter table public.profiles add column if not exists organization_name text not null default '';
alter table public.profiles add column if not exists created_at timestamptz not null default now();
alter table public.profiles add column if not exists updated_at timestamptz not null default now();

create table if not exists public.reports (
  id bigint primary key,
  tracking_code text not null,
  issue_type text not null,
  location_name text not null,
  area text not null default '',
  description text not null default '',
  latitude double precision,
  longitude double precision,
  urgency text not null default '',
  reporter_type text not null default 'Public Reporter',
  reporter_name text not null default '',
  reporter_phone text not null default '',
  reporter_email text not null default '',
  is_anonymous boolean not null default true,
  near_sensitive_area text not null default 'No',
  risk_score integer not null default 0,
  risk_label text not null default 'Low',
  status text not null default 'Reported',
  created_at timestamptz not null default now(),
  photo_url text not null default ''
);

alter table public.reports add column if not exists tracking_code text;
alter table public.reports add column if not exists issue_type text;
alter table public.reports add column if not exists location_name text;
alter table public.reports add column if not exists area text;
alter table public.reports add column if not exists description text;
alter table public.reports add column if not exists latitude double precision;
alter table public.reports add column if not exists longitude double precision;
alter table public.reports add column if not exists urgency text;
alter table public.reports add column if not exists reporter_type text;
alter table public.reports add column if not exists reporter_name text;
alter table public.reports add column if not exists reporter_phone text;
alter table public.reports add column if not exists reporter_email text;
alter table public.reports add column if not exists is_anonymous boolean;
alter table public.reports add column if not exists near_sensitive_area text;
alter table public.reports add column if not exists risk_score integer;
alter table public.reports add column if not exists risk_label text;
alter table public.reports add column if not exists status text;
alter table public.reports add column if not exists created_at timestamptz;
alter table public.reports add column if not exists photo_url text;

create table if not exists public.report_updates (
  id bigint generated by default as identity primary key,
  report_id bigint not null,
  status text not null,
  note text not null default '',
  updated_by uuid references auth.users(id) on delete set null,
  updated_by_name text not null default 'Make Kenya Clean',
  created_at timestamptz not null default now()
);

alter table public.report_updates add column if not exists report_id bigint;
alter table public.report_updates add column if not exists status text;
alter table public.report_updates add column if not exists note text;
alter table public.report_updates add column if not exists updated_by uuid;
alter table public.report_updates add column if not exists updated_by_name text;
alter table public.report_updates add column if not exists created_at timestamptz;

create table if not exists public.access_requests (
  id bigint generated by default as identity primary key,
  full_name text not null,
  email text not null,
  phone text not null default '',
  requested_role text not null,
  area text not null default '',
  organization_name text not null default '',
  reason text not null default '',
  status text not null default 'Pending',
  reviewed_by uuid references auth.users(id) on delete set null,
  reviewed_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.access_requests add column if not exists full_name text;
alter table public.access_requests add column if not exists id bigint generated by default as identity;
alter table public.access_requests add column if not exists email text;
alter table public.access_requests add column if not exists phone text;
alter table public.access_requests add column if not exists requested_role text;
alter table public.access_requests add column if not exists area text;
alter table public.access_requests add column if not exists organization_name text;
alter table public.access_requests add column if not exists reason text;
alter table public.access_requests add column if not exists status text;
alter table public.access_requests add column if not exists reviewed_by uuid;
alter table public.access_requests add column if not exists reviewed_at timestamptz;
alter table public.access_requests add column if not exists created_at timestamptz;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'profiles_role_check'
      and conrelid = 'public.profiles'::regclass
  ) then
    alter table public.profiles
      add constraint profiles_role_check
      check (role in ('pending', 'admin', 'champion', 'organization')) not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'reports_status_check'
      and conrelid = 'public.reports'::regclass
  ) then
    alter table public.reports
      add constraint reports_status_check
      check (status in ('Reported', 'Verified', 'Assigned', 'In Progress', 'Resolved', 'Community Confirmed')) not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'reports_risk_score_check'
      and conrelid = 'public.reports'::regclass
  ) then
    alter table public.reports
      add constraint reports_risk_score_check
      check (risk_score is null or (risk_score >= 0 and risk_score <= 100)) not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'access_requests_status_check'
      and conrelid = 'public.access_requests'::regclass
  ) then
    alter table public.access_requests
      add constraint access_requests_status_check
      check (status in ('Pending', 'Approved', 'Rejected')) not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'access_requests_requested_role_check'
      and conrelid = 'public.access_requests'::regclass
  ) then
    alter table public.access_requests
      add constraint access_requests_requested_role_check
      check (requested_role in ('champion', 'organization')) not valid;
  end if;
end $$;

create index if not exists reports_tracking_code_idx on public.reports (tracking_code);
create index if not exists reports_created_at_idx on public.reports (created_at desc);
create index if not exists reports_status_idx on public.reports (status);
create index if not exists reports_risk_score_idx on public.reports (risk_score desc);
create index if not exists report_updates_report_id_created_at_idx on public.report_updates (report_id, created_at);
create index if not exists profiles_role_idx on public.profiles (role);
create index if not exists access_requests_status_created_at_idx on public.access_requests (status, created_at desc);
create index if not exists access_requests_email_idx on public.access_requests (lower(email));

create or replace function public.current_profile_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select role
  from public.profiles
  where id = auth.uid()
  limit 1
$$;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(public.current_profile_role() = 'admin', false)
$$;

create or replace function public.is_staff()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(public.current_profile_role() in ('admin', 'champion', 'organization'), false)
$$;

-- Public-safe report view. This view intentionally omits reporter_name,
-- reporter_phone, and reporter_email. Base table SELECT is revoked from anon,
-- so public clients cannot bypass the view to read private reporter columns.
create or replace view public.public_reports
with (security_barrier = true)
as
select
  id,
  tracking_code,
  issue_type,
  location_name,
  area,
  description,
  latitude,
  longitude,
  urgency,
  reporter_type,
  is_anonymous,
  near_sensitive_area,
  risk_score,
  risk_label,
  status,
  created_at,
  photo_url
from public.reports;

alter table public.profiles enable row level security;
alter table public.reports enable row level security;
alter table public.report_updates enable row level security;
alter table public.access_requests enable row level security;

revoke all on public.profiles from anon, authenticated;
revoke all on public.reports from anon, authenticated;
revoke all on public.report_updates from anon, authenticated;
revoke all on public.access_requests from anon, authenticated;
revoke all on public.public_reports from anon, authenticated;

grant select on public.public_reports to anon, authenticated;
grant select, insert on public.reports to authenticated;
grant update(status) on public.reports to authenticated;
grant insert on public.reports to anon;
grant select, insert on public.report_updates to anon, authenticated;
grant select on public.profiles to authenticated;
grant insert on public.access_requests to anon, authenticated;
grant select on public.access_requests to authenticated;

do $$
declare
  policy_record record;
begin
  for policy_record in
    select schemaname, tablename, policyname
    from pg_policies
    where schemaname = 'public'
      and tablename in (
        'profiles',
        'reports',
        'report_updates',
        'access_requests'
      )
  loop
    execute format(
      'drop policy if exists %I on %I.%I',
      policy_record.policyname,
      policy_record.schemaname,
      policy_record.tablename
    );
  end loop;
end $$;

drop policy if exists "profiles_select_own_or_admin" on public.profiles;
create policy "profiles_select_own_or_admin"
on public.profiles
for select
to authenticated
using (id = auth.uid() or public.is_admin());

drop policy if exists "reports_public_insert_reported" on public.reports;
create policy "reports_public_insert_reported"
on public.reports
for insert
to anon, authenticated
with check (
  coalesce(status, 'Reported') = 'Reported'
);

drop policy if exists "reports_staff_select" on public.reports;
create policy "reports_staff_select"
on public.reports
for select
to authenticated
using (public.is_staff());

drop policy if exists "reports_admin_update" on public.reports;
create policy "reports_admin_update"
on public.reports
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "reports_champion_verify" on public.reports;
create policy "reports_champion_verify"
on public.reports
for update
to authenticated
using (
  status = 'Reported'
  and public.current_profile_role() in ('admin', 'champion')
)
with check (
  status = 'Verified'
  and public.current_profile_role() in ('admin', 'champion')
);

drop policy if exists "report_updates_public_select" on public.report_updates;
create policy "report_updates_public_select"
on public.report_updates
for select
to anon, authenticated
using (true);

drop policy if exists "report_updates_public_initial_insert" on public.report_updates;
create policy "report_updates_public_initial_insert"
on public.report_updates
for insert
to anon
with check (
  status = 'Reported'
  and updated_by is null
);

drop policy if exists "report_updates_staff_insert" on public.report_updates;
create policy "report_updates_staff_insert"
on public.report_updates
for insert
to authenticated
with check (public.is_staff());

drop policy if exists "access_requests_public_insert_pending" on public.access_requests;
create policy "access_requests_public_insert_pending"
on public.access_requests
for insert
to anon, authenticated
with check (
  coalesce(status, 'Pending') = 'Pending'
  and reviewed_by is null
  and reviewed_at is null
  and requested_role in ('champion', 'organization')
);

drop policy if exists "access_requests_admin_select" on public.access_requests;
create policy "access_requests_admin_select"
on public.access_requests
for select
to authenticated
using (public.is_admin());

create or replace function public.reject_access_request(request_id text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_request public.access_requests%rowtype;
begin
  if auth.uid() is null then
    raise exception 'Authentication required' using errcode = '28000';
  end if;

  if not public.is_admin() then
    raise exception 'Admin role required' using errcode = '42501';
  end if;

  select *
  into v_request
  from public.access_requests
  where id::text = request_id
  limit 1;

  if not found then
    raise exception 'Access request not found' using errcode = 'P0002';
  end if;

  if v_request.status <> 'Pending' then
    raise exception 'Only pending access requests can be rejected' using errcode = 'P0001';
  end if;

  update public.access_requests
  set
    status = 'Rejected',
    reviewed_by = auth.uid(),
    reviewed_at = now()
  where id::text = request_id
    and status = 'Pending';

  if not found then
    raise exception 'Access request was already reviewed' using errcode = 'P0001';
  end if;

  return jsonb_build_object(
    'success', true,
    'request_id', request_id,
    'status', 'Rejected'
  );
end;
$$;

revoke all on function public.reject_access_request(text) from public;
grant execute on function public.reject_access_request(text) to authenticated;
grant execute on function public.current_profile_role() to anon, authenticated;
grant execute on function public.is_admin() to anon, authenticated;
grant execute on function public.is_staff() to anon, authenticated;

insert into storage.buckets (id, name, public)
values ('report-photos', 'report-photos', true)
on conflict (id) do nothing;

do $$
declare
  policy_record record;
begin
  for policy_record in
    select policyname
    from pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and (
        coalesce(qual, '') like '%report-photos%'
        or coalesce(with_check, '') like '%report-photos%'
      )
  loop
    execute format(
      'drop policy if exists %I on storage.objects',
      policy_record.policyname
    );
  end loop;
end $$;

drop policy if exists "report_photos_public_read" on storage.objects;
create policy "report_photos_public_read"
on storage.objects
for select
to anon, authenticated
using (bucket_id = 'report-photos');

drop policy if exists "report_photos_public_insert" on storage.objects;
create policy "report_photos_public_insert"
on storage.objects
for insert
to anon, authenticated
with check (
  bucket_id = 'report-photos'
);
