-- End-to-end report response and resolution workflow.
--
-- This migration is non-destructive. It adds operational tables, helper
-- functions, policies, and RPC transitions without rewriting existing report
-- ids, tracking codes, or reports.created_at values.

create extension if not exists pgcrypto;

alter table public.profiles
  add column if not exists organization_id uuid;

create table if not exists public.organizations (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  organization_type text not null default 'Other',
  area text not null default '',
  contact_email text not null default '',
  contact_phone text not null default '',
  status text not null default 'Active',
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.report_assignments (
  id bigint generated by default as identity primary key,
  report_id bigint not null references public.reports(id) on delete cascade,
  organization_id uuid not null references public.organizations(id) on delete restrict,
  assigned_by uuid references auth.users(id) on delete set null,
  assigned_at timestamptz not null default now(),
  accepted_by uuid references auth.users(id) on delete set null,
  accepted_at timestamptz,
  status text not null default 'Assigned',
  note text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.report_actions (
  id bigint generated by default as identity primary key,
  report_id bigint not null references public.reports(id) on delete cascade,
  assignment_id bigint not null references public.report_assignments(id) on delete cascade,
  organization_id uuid not null references public.organizations(id) on delete restrict,
  action_type text not null default 'Other',
  note text not null default '',
  visibility text not null default 'Public',
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.resolution_evidence (
  id bigint generated by default as identity primary key,
  report_id bigint not null references public.reports(id) on delete cascade,
  assignment_id bigint not null references public.report_assignments(id) on delete cascade,
  organization_id uuid not null references public.organizations(id) on delete restrict,
  photo_path text not null default '',
  note text not null default '',
  completed_at date,
  submitted_by uuid references auth.users(id) on delete set null,
  submitted_at timestamptz not null default now(),
  review_status text not null default 'Submitted',
  reviewed_by uuid references auth.users(id) on delete set null,
  reviewed_at timestamptz,
  review_note text not null default ''
);

create table if not exists public.community_confirmations (
  id bigint generated by default as identity primary key,
  report_id bigint not null references public.reports(id) on delete cascade,
  tracking_code text not null,
  confirmation text not null,
  note text not null default '',
  submitted_at timestamptz not null default now(),
  review_status text not null default 'Pending',
  reviewed_by uuid references auth.users(id) on delete set null,
  reviewed_at timestamptz,
  review_note text not null default '',
  created_at timestamptz not null default now()
);

alter table public.resolution_evidence
  add column if not exists photo_path text not null default '';

alter table public.community_confirmations
  add column if not exists submitted_at timestamptz not null default now(),
  add column if not exists review_status text not null default 'Pending',
  add column if not exists reviewed_by uuid references auth.users(id) on delete set null,
  add column if not exists reviewed_at timestamptz,
  add column if not exists review_note text not null default '';

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'organizations_type_check'
      and conrelid = 'public.organizations'::regclass
  ) then
    alter table public.organizations
      add constraint organizations_type_check
      check (organization_type in ('County', 'NGO', 'School', 'Estate', 'Institution', 'Utility', 'Community Organization', 'Other')) not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'organizations_status_check'
      and conrelid = 'public.organizations'::regclass
  ) then
    alter table public.organizations
      add constraint organizations_status_check
      check (status in ('Active', 'Suspended')) not valid;
  end if;

  if exists (
    select 1 from pg_constraint
    where conname = 'reports_status_check'
      and conrelid = 'public.reports'::regclass
  ) then
    alter table public.reports
      drop constraint reports_status_check;
  end if;

  alter table public.reports
    add constraint reports_status_check
    check (status in ('Reported', 'Verified', 'Assigned', 'In Progress', 'Resolution Submitted', 'Resolved', 'Community Confirmed')) not valid;

  if not exists (
    select 1 from pg_constraint
    where conname = 'report_assignments_status_check'
      and conrelid = 'public.report_assignments'::regclass
  ) then
    alter table public.report_assignments
      add constraint report_assignments_status_check
      check (status in ('Assigned', 'Accepted', 'Declined', 'Completed', 'Cancelled')) not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'report_actions_action_type_check'
      and conrelid = 'public.report_actions'::regclass
  ) then
    alter table public.report_actions
      add constraint report_actions_action_type_check
      check (action_type in ('Inspection', 'Team Dispatched', 'Work Started', 'Repair', 'Cleaning', 'Drainage Clearing', 'Water Testing', 'Follow-up', 'Other')) not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'report_actions_visibility_check'
      and conrelid = 'public.report_actions'::regclass
  ) then
    alter table public.report_actions
      add constraint report_actions_visibility_check
      check (visibility in ('Public', 'Staff Only')) not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'resolution_evidence_review_status_check'
      and conrelid = 'public.resolution_evidence'::regclass
  ) then
    alter table public.resolution_evidence
      add constraint resolution_evidence_review_status_check
      check (review_status in ('Submitted', 'Approved', 'Rejected')) not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'community_confirmations_confirmation_check'
      and conrelid = 'public.community_confirmations'::regclass
  ) then
    alter table public.community_confirmations
      add constraint community_confirmations_confirmation_check
      check (confirmation in ('Confirmed', 'Disputed')) not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'community_confirmations_review_status_check'
      and conrelid = 'public.community_confirmations'::regclass
  ) then
    alter table public.community_confirmations
      add constraint community_confirmations_review_status_check
      check (review_status in ('Pending', 'Approved', 'Rejected')) not valid;
  end if;
end $$;

create unique index if not exists organizations_name_key on public.organizations (lower(name));
create index if not exists profiles_organization_id_idx on public.profiles (organization_id);
create index if not exists organizations_status_idx on public.organizations (status);
create index if not exists report_assignments_report_id_idx on public.report_assignments (report_id);
create index if not exists report_assignments_organization_id_idx on public.report_assignments (organization_id);
create index if not exists report_assignments_status_idx on public.report_assignments (status);
create unique index if not exists report_assignments_one_active_idx
  on public.report_assignments (report_id)
  where status in ('Assigned', 'Accepted');
create index if not exists report_actions_assignment_id_created_at_idx
  on public.report_actions (assignment_id, created_at desc);
create index if not exists report_actions_report_id_created_at_idx
  on public.report_actions (report_id, created_at desc);
create index if not exists resolution_evidence_assignment_status_idx
  on public.resolution_evidence (assignment_id, review_status, submitted_at desc);
create index if not exists community_confirmations_report_id_idx
  on public.community_confirmations (report_id, created_at desc);
create unique index if not exists community_confirmations_one_pending_idx
  on public.community_confirmations (report_id)
  where review_status = 'Pending';

insert into public.organizations (
  name,
  organization_type,
  area,
  contact_email,
  status,
  created_by
)
select distinct
  coalesce(nullif(trim(organization_name), ''), full_name, 'Unnamed Organization') as name,
  'Other',
  coalesce(area, ''),
  '',
  'Active',
  id
from public.profiles
where role = 'organization'
  and organization_id is null
  and not exists (
    select 1
    from public.organizations existing
    where lower(existing.name) = lower(coalesce(nullif(trim(profiles.organization_name), ''), profiles.full_name, 'Unnamed Organization'))
  );

update public.profiles profile
set organization_id = organization.id
from public.organizations organization
where profile.role = 'organization'
  and profile.organization_id is null
  and lower(organization.name) = lower(coalesce(nullif(trim(profile.organization_name), ''), profile.full_name, 'Unnamed Organization'));

create or replace function public.profile_organization_id()
returns uuid
language sql
stable
security definer
set search_path = public
as $$
  select organization_id
  from public.profiles
  where id = auth.uid()
  limit 1
$$;

create or replace function public.is_organization_member(target_organization_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    public.current_profile_role() = 'organization'
    and public.profile_organization_id() = target_organization_id,
    false
  )
$$;

create or replace function public.assignment_actor_name(actor_id uuid)
returns text
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    (select nullif(full_name, '') from public.profiles where id = actor_id),
    'Make Kenya Clean Staff'
  )
$$;

create or replace function public.can_write_resolution_evidence_object(object_name text)
returns boolean
language plpgsql
stable
security definer
set search_path = public, storage
as $$
declare
  v_parts text[];
  v_organization_id uuid;
  v_assignment_id bigint;
begin
  if auth.uid() is null then
    return false;
  end if;

  if public.current_profile_role() <> 'organization' then
    return false;
  end if;

  v_parts := storage.foldername(object_name);

  if array_length(v_parts, 1) < 2 then
    return false;
  end if;

  begin
    v_organization_id := v_parts[1]::uuid;
    v_assignment_id := v_parts[2]::bigint;
  exception when others then
    return false;
  end;

  if not public.is_organization_member(v_organization_id) then
    return false;
  end if;

  return exists (
    select 1
    from public.report_assignments assignment
    join public.reports report on report.id = assignment.report_id
    where assignment.id = v_assignment_id
      and assignment.organization_id = v_organization_id
      and assignment.status = 'Accepted'
      and report.status = 'In Progress'
  );
end;
$$;

create or replace function public.can_read_resolution_evidence_object(object_name text)
returns boolean
language plpgsql
stable
security definer
set search_path = public, storage
as $$
declare
  v_parts text[];
  v_organization_id uuid;
  v_assignment_id bigint;
begin
  if auth.uid() is null then
    return false;
  end if;

  if public.is_admin() then
    return true;
  end if;

  if public.current_profile_role() <> 'organization' then
    return false;
  end if;

  v_parts := storage.foldername(object_name);

  if array_length(v_parts, 1) < 2 then
    return false;
  end if;

  begin
    v_organization_id := v_parts[1]::uuid;
    v_assignment_id := v_parts[2]::bigint;
  exception when others then
    return false;
  end;

  if not public.is_organization_member(v_organization_id) then
    return false;
  end if;

  return exists (
    select 1
    from public.report_assignments assignment
    where assignment.id = v_assignment_id
      and assignment.organization_id = v_organization_id
  );
end;
$$;

create or replace function public.assign_report_to_organization(
  p_report_id bigint,
  p_organization_id uuid,
  p_note text default ''
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_report public.reports%rowtype;
  v_organization public.organizations%rowtype;
  v_assignment public.report_assignments%rowtype;
  v_actor_name text;
begin
  if auth.uid() is null then
    raise exception 'Authentication required' using errcode = '28000';
  end if;

  if not public.is_admin() then
    raise exception 'Admin role required' using errcode = '42501';
  end if;

  select * into v_report
  from public.reports
  where id = p_report_id
  for update;

  if not found then
    raise exception 'Report not found' using errcode = 'P0002';
  end if;

  if v_report.status <> 'Verified' then
    raise exception 'Only verified reports can be assigned' using errcode = 'P0001';
  end if;

  select * into v_organization
  from public.organizations
  where id = p_organization_id
    and status = 'Active';

  if not found then
    raise exception 'Active organization not found' using errcode = 'P0002';
  end if;

  if exists (
    select 1
    from public.report_assignments
    where report_id = p_report_id
      and status in ('Assigned', 'Accepted')
  ) then
    raise exception 'Report already has an active assignment' using errcode = 'P0001';
  end if;

  insert into public.report_assignments (
    report_id,
    organization_id,
    assigned_by,
    note
  )
  values (
    p_report_id,
    p_organization_id,
    auth.uid(),
    coalesce(p_note, '')
  )
  returning * into v_assignment;

  update public.reports
  set status = 'Assigned'
  where id = p_report_id;

  v_actor_name := public.assignment_actor_name(auth.uid());

  insert into public.report_updates (
    report_id,
    status,
    note,
    updated_by,
    updated_by_name
  )
  values (
    p_report_id,
    'Assigned',
    'Assigned to ' || v_organization.name || case when coalesce(p_note, '') <> '' then ': ' || p_note else '.' end,
    auth.uid(),
    v_actor_name
  );

  return jsonb_build_object(
    'success', true,
    'assignment_id', v_assignment.id,
    'report_id', p_report_id,
    'organization_id', p_organization_id,
    'status', 'Assigned'
  );
end;
$$;

create or replace function public.accept_report_assignment(p_assignment_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_assignment public.report_assignments%rowtype;
  v_organization public.organizations%rowtype;
  v_actor_name text;
begin
  if auth.uid() is null then
    raise exception 'Authentication required' using errcode = '28000';
  end if;

  select * into v_assignment
  from public.report_assignments
  where id = p_assignment_id
  for update;

  if not found then
    raise exception 'Assignment not found' using errcode = 'P0002';
  end if;

  if not public.is_organization_member(v_assignment.organization_id) then
    raise exception 'Assigned organization role required' using errcode = '42501';
  end if;

  if v_assignment.status <> 'Assigned' then
    raise exception 'Only newly assigned cases can be accepted' using errcode = 'P0001';
  end if;

  select * into v_organization
  from public.organizations
  where id = v_assignment.organization_id;

  update public.report_assignments
  set
    status = 'Accepted',
    accepted_by = auth.uid(),
    accepted_at = now(),
    updated_at = now()
  where id = p_assignment_id;

  update public.reports
  set status = 'In Progress'
  where id = v_assignment.report_id;

  v_actor_name := public.assignment_actor_name(auth.uid());

  insert into public.report_updates (
    report_id,
    status,
    note,
    updated_by,
    updated_by_name
  )
  values (
    v_assignment.report_id,
    'In Progress',
    coalesce(v_organization.name, 'Assigned organization') || ' accepted the assignment and started response work.',
    auth.uid(),
    v_actor_name
  );

  return jsonb_build_object(
    'success', true,
    'assignment_id', p_assignment_id,
    'report_id', v_assignment.report_id,
    'status', 'In Progress'
  );
end;
$$;

create or replace function public.add_report_action(
  p_assignment_id bigint,
  p_action_type text,
  p_note text,
  p_visibility text default 'Public'
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_assignment public.report_assignments%rowtype;
  v_report public.reports%rowtype;
  v_action public.report_actions%rowtype;
  v_actor_name text;
  v_visibility text;
begin
  if auth.uid() is null then
    raise exception 'Authentication required' using errcode = '28000';
  end if;

  select * into v_assignment
  from public.report_assignments
  where id = p_assignment_id;

  if not found then
    raise exception 'Assignment not found' using errcode = 'P0002';
  end if;

  if not public.is_organization_member(v_assignment.organization_id) then
    raise exception 'Assigned organization role required' using errcode = '42501';
  end if;

  if v_assignment.status <> 'Accepted' then
    raise exception 'Actions can only be added to accepted assignments' using errcode = 'P0001';
  end if;

  select * into v_report
  from public.reports
  where id = v_assignment.report_id;

  if v_report.status not in ('In Progress', 'Resolution Submitted') then
    raise exception 'Report is not active for operational updates' using errcode = 'P0001';
  end if;

  v_visibility := case when p_visibility = 'Staff Only' then 'Staff Only' else 'Public' end;

  insert into public.report_actions (
    report_id,
    assignment_id,
    organization_id,
    action_type,
    note,
    visibility,
    created_by
  )
  values (
    v_assignment.report_id,
    p_assignment_id,
    v_assignment.organization_id,
    coalesce(nullif(p_action_type, ''), 'Other'),
    coalesce(p_note, ''),
    v_visibility,
    auth.uid()
  )
  returning * into v_action;

  if v_visibility = 'Public' then
    v_actor_name := public.assignment_actor_name(auth.uid());

    insert into public.report_updates (
      report_id,
      status,
      note,
      updated_by,
      updated_by_name
    )
    values (
      v_assignment.report_id,
      v_action.action_type,
      coalesce(nullif(v_action.note, ''), 'Operational update added.'),
      auth.uid(),
      v_actor_name
    );
  end if;

  return jsonb_build_object(
    'success', true,
    'action_id', v_action.id,
    'assignment_id', p_assignment_id
  );
end;
$$;

create or replace function public.submit_resolution_evidence(
  p_assignment_id bigint,
  p_photo_path text,
  p_note text,
  p_completed_at date default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_assignment public.report_assignments%rowtype;
  v_evidence public.resolution_evidence%rowtype;
  v_actor_name text;
begin
  if auth.uid() is null then
    raise exception 'Authentication required' using errcode = '28000';
  end if;

  select * into v_assignment
  from public.report_assignments
  where id = p_assignment_id
  for update;

  if not found then
    raise exception 'Assignment not found' using errcode = 'P0002';
  end if;

  if not public.is_organization_member(v_assignment.organization_id) then
    raise exception 'Assigned organization role required' using errcode = '42501';
  end if;

  if v_assignment.status <> 'Accepted' then
    raise exception 'Resolution evidence can only be submitted for accepted assignments' using errcode = 'P0001';
  end if;

  if coalesce(p_photo_path, '') = '' then
    raise exception 'Resolution evidence photo is required' using errcode = 'P0001';
  end if;

  if not public.can_write_resolution_evidence_object(p_photo_path) then
    raise exception 'Resolution evidence path is not allowed for this assignment' using errcode = '42501';
  end if;

  insert into public.resolution_evidence (
    report_id,
    assignment_id,
    organization_id,
    photo_path,
    note,
    completed_at,
    submitted_by
  )
  values (
    v_assignment.report_id,
    p_assignment_id,
    v_assignment.organization_id,
    p_photo_path,
    left(coalesce(p_note, ''), 1000),
    p_completed_at,
    auth.uid()
  )
  returning * into v_evidence;

  update public.reports
  set status = 'Resolution Submitted'
  where id = v_assignment.report_id;

  v_actor_name := public.assignment_actor_name(auth.uid());

  insert into public.report_updates (
    report_id,
    status,
    note,
    updated_by,
    updated_by_name
  )
  values (
    v_assignment.report_id,
    'Resolution Submitted',
    coalesce(nullif(p_note, ''), 'Resolution evidence submitted for review.'),
    auth.uid(),
    v_actor_name
  );

  return jsonb_build_object(
    'success', true,
    'evidence_id', v_evidence.id,
    'report_id', v_assignment.report_id,
    'status', 'Resolution Submitted'
  );
end;
$$;

create or replace function public.review_resolution_evidence(
  p_evidence_id bigint,
  p_approved boolean,
  p_review_note text default ''
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_evidence public.resolution_evidence%rowtype;
  v_actor_name text;
  v_new_report_status text;
  v_assignment_status text;
begin
  if auth.uid() is null then
    raise exception 'Authentication required' using errcode = '28000';
  end if;

  if not public.is_admin() then
    raise exception 'Admin role required' using errcode = '42501';
  end if;

  select * into v_evidence
  from public.resolution_evidence
  where id = p_evidence_id
  for update;

  if not found then
    raise exception 'Resolution evidence not found' using errcode = 'P0002';
  end if;

  if v_evidence.review_status <> 'Submitted' then
    raise exception 'Resolution evidence has already been reviewed' using errcode = 'P0001';
  end if;

  v_new_report_status := case when p_approved then 'Resolved' else 'In Progress' end;
  v_assignment_status := case when p_approved then 'Completed' else 'Accepted' end;

  update public.resolution_evidence
  set
    review_status = case when p_approved then 'Approved' else 'Rejected' end,
    reviewed_by = auth.uid(),
    reviewed_at = now(),
    review_note = coalesce(p_review_note, '')
  where id = p_evidence_id;

  update public.report_assignments
  set
    status = v_assignment_status,
    updated_at = now()
  where id = v_evidence.assignment_id;

  update public.reports
  set status = v_new_report_status
  where id = v_evidence.report_id;

  v_actor_name := public.assignment_actor_name(auth.uid());

  insert into public.report_updates (
    report_id,
    status,
    note,
    updated_by,
    updated_by_name
  )
  values (
    v_evidence.report_id,
    v_new_report_status,
    case
      when p_approved then coalesce(nullif(p_review_note, ''), 'Resolution evidence approved.')
      else coalesce(nullif(p_review_note, ''), 'Resolution evidence needs more work.')
    end,
    auth.uid(),
    v_actor_name
  );

  return jsonb_build_object(
    'success', true,
    'evidence_id', p_evidence_id,
    'report_id', v_evidence.report_id,
    'status', v_new_report_status
  );
end;
$$;

create or replace function public.submit_community_confirmation(
  p_tracking_code text,
  p_confirmation text,
  p_note text default ''
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_report public.reports%rowtype;
  v_confirmation text;
  v_tracking_code text;
  v_note text;
  v_confirmation_row public.community_confirmations%rowtype;
begin
  v_tracking_code := upper(trim(coalesce(p_tracking_code, '')));
  v_note := left(trim(coalesce(p_note, '')), 500);

  if v_tracking_code = '' or length(v_tracking_code) > 64 then
    raise exception 'A valid tracking code is required' using errcode = 'P0001';
  end if;

  if p_confirmation not in ('Confirmed', 'Disputed') then
    raise exception 'Confirmation must be Confirmed or Disputed' using errcode = 'P0001';
  end if;

  v_confirmation := p_confirmation;

  select * into v_report
  from public.reports
  where tracking_code = v_tracking_code
  for update;

  if not found then
    raise exception 'Report not found' using errcode = 'P0002';
  end if;

  if v_report.status <> 'Resolved' then
    raise exception 'Only resolved reports can receive community confirmation' using errcode = 'P0001';
  end if;

  if exists (
    select 1
    from public.community_confirmations
    where report_id = v_report.id
      and review_status = 'Pending'
  ) then
    raise exception 'Community feedback is already pending review for this report' using errcode = 'P0001';
  end if;

  insert into public.community_confirmations (
    report_id,
    tracking_code,
    confirmation,
    note,
    review_status
  )
  values (
    v_report.id,
    v_report.tracking_code,
    v_confirmation,
    v_note,
    'Pending'
  )
  returning * into v_confirmation_row;

  insert into public.report_updates (
    report_id,
    status,
    note,
    updated_by_name
  )
  values (
    v_report.id,
    'Community Feedback Submitted',
    case
      when v_confirmation = 'Confirmed' then coalesce(nullif(v_note, ''), 'Community feedback submitted for admin review.')
      else coalesce(nullif(v_note, ''), 'Community dispute submitted for admin review.')
    end,
    'Community Feedback'
  );

  return jsonb_build_object(
    'success', true,
    'confirmation_id', v_confirmation_row.id,
    'report_id', v_report.id,
    'confirmation', v_confirmation,
    'review_status', 'Pending',
    'status', v_report.status
  );
end;
$$;

create or replace function public.review_community_confirmation(
  p_confirmation_id bigint,
  p_decision text,
  p_review_note text default ''
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_confirmation public.community_confirmations%rowtype;
  v_actor_name text;
  v_new_report_status text;
begin
  if auth.uid() is null then
    raise exception 'Authentication required' using errcode = '28000';
  end if;

  if not public.is_admin() then
    raise exception 'Admin role required' using errcode = '42501';
  end if;

  if p_decision not in ('Approved', 'Rejected') then
    raise exception 'Decision must be Approved or Rejected' using errcode = 'P0001';
  end if;

  select * into v_confirmation
  from public.community_confirmations
  where id = p_confirmation_id
  for update;

  if not found then
    raise exception 'Community confirmation not found' using errcode = 'P0002';
  end if;

  if v_confirmation.review_status <> 'Pending' then
    raise exception 'Community confirmation has already been reviewed' using errcode = 'P0001';
  end if;

  update public.community_confirmations
  set
    review_status = p_decision,
    reviewed_by = auth.uid(),
    reviewed_at = now(),
    review_note = left(coalesce(p_review_note, ''), 1000)
  where id = p_confirmation_id;

  v_actor_name := public.assignment_actor_name(auth.uid());

  if p_decision = 'Approved' then
    v_new_report_status := case
      when v_confirmation.confirmation = 'Confirmed' then 'Community Confirmed'
      else 'In Progress'
    end;

    update public.reports
    set status = v_new_report_status
    where id = v_confirmation.report_id
      and status = 'Resolved';

    if not found then
      raise exception 'Report must still be Resolved to approve community feedback' using errcode = 'P0001';
    end if;

    if v_confirmation.confirmation = 'Disputed' then
      update public.report_assignments
      set
        status = 'Accepted',
        updated_at = now()
      where report_id = v_confirmation.report_id
        and status = 'Completed';
    end if;

    insert into public.report_updates (
      report_id,
      status,
      note,
      updated_by,
      updated_by_name
    )
    values (
      v_confirmation.report_id,
      v_new_report_status,
      case
        when v_confirmation.confirmation = 'Confirmed' then coalesce(nullif(p_review_note, ''), 'Admin approved community confirmation.')
        else coalesce(nullif(p_review_note, ''), 'Admin approved community dispute and returned the case to active work.')
      end,
      auth.uid(),
      v_actor_name
    );
  else
    insert into public.report_updates (
      report_id,
      status,
      note,
      updated_by,
      updated_by_name
    )
    values (
      v_confirmation.report_id,
      'Community Feedback Rejected',
      coalesce(nullif(p_review_note, ''), 'Admin rejected community feedback.'),
      auth.uid(),
      v_actor_name
    );
  end if;

  return jsonb_build_object(
    'success', true,
    'confirmation_id', p_confirmation_id,
    'report_id', v_confirmation.report_id,
    'decision', p_decision,
    'status', coalesce(v_new_report_status, 'Resolved')
  );
end;
$$;

alter table public.organizations enable row level security;
alter table public.report_assignments enable row level security;
alter table public.report_actions enable row level security;
alter table public.resolution_evidence enable row level security;
alter table public.community_confirmations enable row level security;

revoke all on public.organizations from anon, authenticated;
revoke all on public.report_assignments from anon, authenticated;
revoke all on public.report_actions from anon, authenticated;
revoke all on public.resolution_evidence from anon, authenticated;
revoke all on public.community_confirmations from anon, authenticated;

grant select on public.organizations to authenticated;
grant select on public.report_assignments to authenticated;
grant select on public.report_actions to anon, authenticated;
grant select on public.resolution_evidence to authenticated;
grant select on public.community_confirmations to authenticated;

grant execute on function public.profile_organization_id() to authenticated;
grant execute on function public.is_organization_member(uuid) to authenticated;
grant execute on function public.assignment_actor_name(uuid) to authenticated;
grant execute on function public.can_write_resolution_evidence_object(text) to authenticated;
grant execute on function public.can_read_resolution_evidence_object(text) to authenticated;
grant execute on function public.assign_report_to_organization(bigint, uuid, text) to authenticated;
grant execute on function public.accept_report_assignment(bigint) to authenticated;
grant execute on function public.add_report_action(bigint, text, text, text) to authenticated;
grant execute on function public.submit_resolution_evidence(bigint, text, text, date) to authenticated;
grant execute on function public.review_resolution_evidence(bigint, boolean, text) to authenticated;
grant execute on function public.submit_community_confirmation(text, text, text) to anon, authenticated;
grant execute on function public.review_community_confirmation(bigint, text, text) to authenticated;

drop policy if exists "reports_staff_select" on public.reports;
drop policy if exists "reports_admin_update" on public.reports;
create policy "reports_admin_champion_or_assigned_org_select"
on public.reports
for select
to authenticated
using (
  public.current_profile_role() in ('admin', 'champion')
  or exists (
    select 1
    from public.report_assignments assignment
    where assignment.report_id = reports.id
      and assignment.status in ('Assigned', 'Accepted', 'Completed')
      and public.is_organization_member(assignment.organization_id)
  )
);

drop policy if exists "profiles_select_own_or_admin" on public.profiles;
create policy "profiles_select_own_or_admin"
on public.profiles
for select
to authenticated
using (id = auth.uid() or public.is_admin() or public.is_organization_member(organization_id));

drop policy if exists "organizations_admin_or_member_select" on public.organizations;
create policy "organizations_admin_or_member_select"
on public.organizations
for select
to authenticated
using (public.is_admin() or public.is_organization_member(id));

drop policy if exists "report_assignments_admin_or_member_select" on public.report_assignments;
create policy "report_assignments_admin_or_member_select"
on public.report_assignments
for select
to authenticated
using (public.is_admin() or public.is_organization_member(organization_id));

drop policy if exists "report_actions_public_or_authorized_select" on public.report_actions;
create policy "report_actions_public_or_authorized_select"
on public.report_actions
for select
to anon, authenticated
using (
  visibility = 'Public'
  or public.is_admin()
  or public.is_organization_member(organization_id)
);

drop policy if exists "resolution_evidence_admin_or_member_select" on public.resolution_evidence;
create policy "resolution_evidence_admin_or_member_select"
on public.resolution_evidence
for select
to authenticated
using (public.is_admin() or public.is_organization_member(organization_id));

drop policy if exists "community_confirmations_public_insert" on public.community_confirmations;

drop policy if exists "community_confirmations_public_select" on public.community_confirmations;
drop policy if exists "community_confirmations_admin_select" on public.community_confirmations;
create policy "community_confirmations_admin_select"
on public.community_confirmations
for select
to authenticated
using (public.is_admin());

insert into storage.buckets (id, name, public)
values ('resolution-evidence', 'resolution-evidence', false)
on conflict (id) do update set public = false;

drop policy if exists "resolution_evidence_org_upload" on storage.objects;
create policy "resolution_evidence_org_upload"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'resolution-evidence'
  and public.can_write_resolution_evidence_object(name)
);

drop policy if exists "resolution_evidence_staff_read" on storage.objects;
drop policy if exists "resolution_evidence_authorized_read" on storage.objects;
create policy "resolution_evidence_authorized_read"
on storage.objects
for select
to authenticated
using (
  bucket_id = 'resolution-evidence'
  and public.can_read_resolution_evidence_object(name)
);
