-- Operations UX support: organization administration and notifications.
--
-- Non-destructive. This migration keeps the deployed report workflow intact and
-- adds secure notification records plus admin-only organization/member RPCs.

create extension if not exists pgcrypto;

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  recipient_user_id uuid references auth.users(id) on delete cascade,
  recipient_email text not null default '',
  type text not null,
  title text not null,
  message text not null default '',
  related_report_id bigint references public.reports(id) on delete cascade,
  related_assignment_id bigint references public.report_assignments(id) on delete set null,
  status text not null default 'Unread',
  delivery_status text not null default 'In App Only',
  email_subject text not null default '',
  email_body text not null default '',
  email_action_url text not null default '',
  sent_at timestamptz,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.notifications
  add column if not exists recipient_user_id uuid references auth.users(id) on delete cascade,
  add column if not exists recipient_email text not null default '',
  add column if not exists type text not null default 'General',
  add column if not exists title text not null default '',
  add column if not exists message text not null default '',
  add column if not exists related_report_id bigint references public.reports(id) on delete cascade,
  add column if not exists related_assignment_id bigint references public.report_assignments(id) on delete set null,
  add column if not exists status text not null default 'Unread',
  add column if not exists delivery_status text not null default 'In App Only',
  add column if not exists email_subject text not null default '',
  add column if not exists email_body text not null default '',
  add column if not exists email_action_url text not null default '',
  add column if not exists sent_at timestamptz,
  add column if not exists read_at timestamptz,
  add column if not exists created_at timestamptz not null default now();

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'notifications_status_check'
      and conrelid = 'public.notifications'::regclass
  ) then
    alter table public.notifications
      add constraint notifications_status_check
      check (status in ('Unread', 'Read')) not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'notifications_delivery_status_check'
      and conrelid = 'public.notifications'::regclass
  ) then
    alter table public.notifications
      add constraint notifications_delivery_status_check
      check (delivery_status in ('In App Only', 'Queued', 'Sent', 'Failed', 'Not Configured')) not valid;
  end if;
end $$;

create index if not exists notifications_recipient_created_at_idx
  on public.notifications (recipient_user_id, created_at desc);
create index if not exists notifications_recipient_unread_idx
  on public.notifications (recipient_user_id, status)
  where status = 'Unread';
create index if not exists notifications_related_report_idx
  on public.notifications (related_report_id, created_at desc);

create or replace function public.report_detail_url(p_tracking_code text)
returns text
language sql
stable
security definer
set search_path = public
as $$
  select '/reports/' || encode(convert_to(coalesce(p_tracking_code, ''), 'utf8'), 'escape')
$$;

create or replace function public.notification_email_body(
  p_title text,
  p_message text,
  p_tracking_code text,
  p_status text,
  p_action_url text
)
returns text
language sql
stable
security definer
set search_path = public
as $$
  select concat(
    'Make Kenya Clean', chr(10),
    'Report. Verify. Clean. Protect.', chr(10), chr(10),
    coalesce(p_title, 'Notification'), chr(10), chr(10),
    coalesce(p_message, ''), chr(10), chr(10),
    case when coalesce(p_tracking_code, '') <> '' then 'Tracking code: ' || p_tracking_code || chr(10) else '' end,
    case when coalesce(p_status, '') <> '' then 'Current status: ' || p_status || chr(10) else '' end,
    case when coalesce(p_action_url, '') <> '' then chr(10) || 'Open report: ' || p_action_url || chr(10) else '' end
  )
$$;

create or replace function public.create_notification_for_profile(
  p_profile_id uuid,
  p_type text,
  p_title text,
  p_message text,
  p_related_report_id bigint default null,
  p_related_assignment_id bigint default null,
  p_email_subject text default '',
  p_email_required boolean default false
)
returns bigint
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_email text;
  v_tracking_code text;
  v_report_status text;
  v_action_url text;
  v_notification_id bigint;
begin
  if p_profile_id is null then
    return null;
  end if;

  select email into v_email
  from auth.users
  where id = p_profile_id;

  select tracking_code, status
  into v_tracking_code, v_report_status
  from public.reports
  where id = p_related_report_id;

  v_action_url := case
    when coalesce(v_tracking_code, '') <> '' then public.report_detail_url(v_tracking_code)
    else ''
  end;

  insert into public.notifications (
    recipient_user_id,
    recipient_email,
    type,
    title,
    message,
    related_report_id,
    related_assignment_id,
    delivery_status,
    email_subject,
    email_body,
    email_action_url
  )
  values (
    p_profile_id,
    coalesce(v_email, ''),
    left(coalesce(p_type, 'General'), 120),
    left(coalesce(p_title, 'Make Kenya Clean notification'), 200),
    left(coalesce(p_message, ''), 1000),
    p_related_report_id,
    p_related_assignment_id,
    case when p_email_required then 'Queued' else 'In App Only' end,
    left(coalesce(p_email_subject, ''), 240),
    public.notification_email_body(p_title, p_message, v_tracking_code, v_report_status, v_action_url),
    v_action_url
  )
  returning id into v_notification_id;

  return v_notification_id;
end;
$$;

create or replace function public.notify_admins(
  p_type text,
  p_title text,
  p_message text,
  p_related_report_id bigint default null,
  p_related_assignment_id bigint default null,
  p_email_subject text default '',
  p_email_required boolean default false
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_profile record;
  v_count integer := 0;
begin
  for v_profile in
    select id
    from public.profiles
    where role = 'admin'
  loop
    perform public.create_notification_for_profile(
      v_profile.id,
      p_type,
      p_title,
      p_message,
      p_related_report_id,
      p_related_assignment_id,
      p_email_subject,
      p_email_required
    );
    v_count := v_count + 1;
  end loop;

  return v_count;
end;
$$;

create or replace function public.notify_organization_members(
  p_organization_id uuid,
  p_type text,
  p_title text,
  p_message text,
  p_related_report_id bigint default null,
  p_related_assignment_id bigint default null,
  p_email_subject text default '',
  p_email_required boolean default false
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_profile record;
  v_count integer := 0;
begin
  if p_organization_id is null then
    return 0;
  end if;

  for v_profile in
    select id
    from public.profiles
    where role = 'organization'
      and organization_id = p_organization_id
  loop
    perform public.create_notification_for_profile(
      v_profile.id,
      p_type,
      p_title,
      p_message,
      p_related_report_id,
      p_related_assignment_id,
      p_email_subject,
      p_email_required
    );
    v_count := v_count + 1;
  end loop;

  return v_count;
end;
$$;

create or replace function public.create_workflow_notifications()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_report public.reports%rowtype;
  v_assignment public.report_assignments%rowtype;
  v_organization public.organizations%rowtype;
begin
  select * into v_report
  from public.reports
  where id = new.report_id;

  if not found then
    return new;
  end if;

  if new.status = 'Verified' then
    perform public.notify_admins(
      'Report Verified',
      'Report verified and ready for assignment',
      'A Maji Champion verified report ' || coalesce(v_report.tracking_code, '') || '. Assign it to a response organization.',
      new.report_id,
      null,
      '',
      false
    );
  elsif new.status = 'Assigned' then
    select * into v_assignment
    from public.report_assignments
    where report_id = new.report_id
      and status in ('Assigned', 'Accepted')
    order by assigned_at desc
    limit 1;

    select * into v_organization
    from public.organizations
    where id = v_assignment.organization_id;

    perform public.notify_organization_members(
      v_assignment.organization_id,
      'Report Assigned',
      'New report assigned to your organization',
      'Report ' || coalesce(v_report.tracking_code, '') || ' has been assigned to ' || coalesce(v_organization.name, 'your organization') || '.',
      new.report_id,
      v_assignment.id,
      'New Make Kenya Clean report assigned to your organization',
      true
    );
  elsif new.status = 'Resolution Submitted' then
    select * into v_assignment
    from public.report_assignments
    where report_id = new.report_id
    order by updated_at desc
    limit 1;

    perform public.notify_admins(
      'Resolution Submitted',
      'Resolution evidence is ready for review',
      'A response organization submitted resolution evidence for report ' || coalesce(v_report.tracking_code, '') || '.',
      new.report_id,
      v_assignment.id,
      'Resolution evidence is ready for review',
      true
    );
  elsif new.status = 'Resolved' then
    select * into v_assignment
    from public.report_assignments
    where report_id = new.report_id
    order by updated_at desc
    limit 1;

    perform public.notify_organization_members(
      v_assignment.organization_id,
      'Resolution Approved',
      'Resolution evidence approved',
      'Report ' || coalesce(v_report.tracking_code, '') || ' has been marked Resolved after admin review.',
      new.report_id,
      v_assignment.id,
      'Your Make Kenya Clean resolution was approved',
      true
    );
  elsif new.status = 'Community Feedback Submitted' then
    perform public.notify_admins(
      'Community Feedback Submitted',
      'Community feedback requires review',
      'Community feedback was submitted for report ' || coalesce(v_report.tracking_code, '') || '. Review it before changing the report status.',
      new.report_id,
      null,
      'Community feedback requires review',
      true
    );
  elsif new.status = 'In Progress' and lower(coalesce(new.note, '')) like any (array['%dispute%', '%needs more work%']) then
    select * into v_assignment
    from public.report_assignments
    where report_id = new.report_id
    order by updated_at desc
    limit 1;

    perform public.notify_organization_members(
      v_assignment.organization_id,
      case when lower(coalesce(new.note, '')) like '%dispute%' then 'Report Reopened' else 'Resolution Rejected' end,
      case when lower(coalesce(new.note, '')) like '%dispute%' then 'A resolved case has been reopened' else 'Resolution evidence needs more work' end,
      coalesce(new.note, 'Report ' || coalesce(v_report.tracking_code, '') || ' requires follow-up.'),
      new.report_id,
      v_assignment.id,
      case when lower(coalesce(new.note, '')) like '%dispute%' then 'A resolved case has been reopened' else 'Your Make Kenya Clean resolution needs more work' end,
      true
    );
  end if;

  return new;
end;
$$;

drop trigger if exists report_updates_create_workflow_notifications on public.report_updates;
create trigger report_updates_create_workflow_notifications
after insert on public.report_updates
for each row
execute function public.create_workflow_notifications();

create or replace function public.mark_notification_read(p_notification_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'Authentication required' using errcode = '28000';
  end if;

  update public.notifications
  set status = 'Read',
      read_at = coalesce(read_at, now())
  where id = p_notification_id
    and recipient_user_id = auth.uid();

  if not found then
    raise exception 'Notification not found' using errcode = 'P0002';
  end if;

  return jsonb_build_object('success', true, 'notification_id', p_notification_id);
end;
$$;

create or replace function public.mark_all_notifications_read()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_count integer;
begin
  if auth.uid() is null then
    raise exception 'Authentication required' using errcode = '28000';
  end if;

  update public.notifications
  set status = 'Read',
      read_at = coalesce(read_at, now())
  where recipient_user_id = auth.uid()
    and status = 'Unread';

  get diagnostics v_count = row_count;

  return jsonb_build_object('success', true, 'updated_count', v_count);
end;
$$;

create or replace function public.create_organization(
  p_name text,
  p_organization_type text default 'Other',
  p_area text default '',
  p_contact_email text default '',
  p_contact_phone text default ''
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_organization public.organizations%rowtype;
  v_type text;
begin
  if auth.uid() is null then
    raise exception 'Authentication required' using errcode = '28000';
  end if;

  if not public.is_admin() then
    raise exception 'Admin role required' using errcode = '42501';
  end if;

  if length(trim(coalesce(p_name, ''))) < 2 then
    raise exception 'Organization name is required' using errcode = 'P0001';
  end if;

  v_type := case
    when p_organization_type in ('County', 'NGO', 'School', 'Estate', 'Institution', 'Utility', 'Community Organization', 'Other') then p_organization_type
    else 'Other'
  end;

  insert into public.organizations (
    name,
    organization_type,
    area,
    contact_email,
    contact_phone,
    status,
    created_by
  )
  values (
    trim(p_name),
    v_type,
    left(trim(coalesce(p_area, '')), 160),
    left(lower(trim(coalesce(p_contact_email, ''))), 254),
    left(trim(coalesce(p_contact_phone, '')), 80),
    'Active',
    auth.uid()
  )
  returning * into v_organization;

  return jsonb_build_object('success', true, 'organization_id', v_organization.id);
end;
$$;

create or replace function public.update_organization(
  p_organization_id uuid,
  p_name text,
  p_organization_type text default 'Other',
  p_area text default '',
  p_contact_email text default '',
  p_contact_phone text default ''
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_type text;
begin
  if auth.uid() is null then
    raise exception 'Authentication required' using errcode = '28000';
  end if;

  if not public.is_admin() then
    raise exception 'Admin role required' using errcode = '42501';
  end if;

  if length(trim(coalesce(p_name, ''))) < 2 then
    raise exception 'Organization name is required' using errcode = 'P0001';
  end if;

  v_type := case
    when p_organization_type in ('County', 'NGO', 'School', 'Estate', 'Institution', 'Utility', 'Community Organization', 'Other') then p_organization_type
    else 'Other'
  end;

  update public.organizations
  set name = trim(p_name),
      organization_type = v_type,
      area = left(trim(coalesce(p_area, '')), 160),
      contact_email = left(lower(trim(coalesce(p_contact_email, ''))), 254),
      contact_phone = left(trim(coalesce(p_contact_phone, '')), 80),
      updated_at = now()
  where id = p_organization_id;

  if not found then
    raise exception 'Organization not found' using errcode = 'P0002';
  end if;

  return jsonb_build_object('success', true, 'organization_id', p_organization_id);
end;
$$;

create or replace function public.set_organization_status(
  p_organization_id uuid,
  p_status text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'Authentication required' using errcode = '28000';
  end if;

  if not public.is_admin() then
    raise exception 'Admin role required' using errcode = '42501';
  end if;

  if p_status not in ('Active', 'Suspended') then
    raise exception 'Status must be Active or Suspended' using errcode = 'P0001';
  end if;

  update public.organizations
  set status = p_status,
      updated_at = now()
  where id = p_organization_id;

  if not found then
    raise exception 'Organization not found' using errcode = 'P0002';
  end if;

  return jsonb_build_object('success', true, 'organization_id', p_organization_id, 'status', p_status);
end;
$$;

create or replace function public.assign_profile_to_organization(
  p_profile_id uuid,
  p_organization_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_profile public.profiles%rowtype;
  v_organization public.organizations%rowtype;
begin
  if auth.uid() is null then
    raise exception 'Authentication required' using errcode = '28000';
  end if;

  if not public.is_admin() then
    raise exception 'Admin role required' using errcode = '42501';
  end if;

  select * into v_profile
  from public.profiles
  where id = p_profile_id
  for update;

  if not found then
    raise exception 'Profile not found' using errcode = 'P0002';
  end if;

  if v_profile.role <> 'organization' then
    raise exception 'Only organization profiles can be assigned to organizations' using errcode = 'P0001';
  end if;

  select * into v_organization
  from public.organizations
  where id = p_organization_id;

  if not found then
    raise exception 'Organization not found' using errcode = 'P0002';
  end if;

  update public.profiles
  set organization_id = p_organization_id,
      organization_name = v_organization.name,
      updated_at = now()
  where id = p_profile_id;

  return jsonb_build_object('success', true, 'profile_id', p_profile_id, 'organization_id', p_organization_id);
end;
$$;

create or replace function public.remove_profile_from_organization(
  p_profile_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_profile public.profiles%rowtype;
begin
  if auth.uid() is null then
    raise exception 'Authentication required' using errcode = '28000';
  end if;

  if not public.is_admin() then
    raise exception 'Admin role required' using errcode = '42501';
  end if;

  select * into v_profile
  from public.profiles
  where id = p_profile_id
  for update;

  if not found then
    raise exception 'Profile not found' using errcode = 'P0002';
  end if;

  if v_profile.role <> 'organization' then
    raise exception 'Only organization profiles can be removed from organization membership' using errcode = 'P0001';
  end if;

  update public.profiles
  set organization_id = null,
      updated_at = now()
  where id = p_profile_id;

  return jsonb_build_object('success', true, 'profile_id', p_profile_id);
end;
$$;

alter table public.notifications enable row level security;

revoke all on public.notifications from anon, authenticated;
grant select on public.notifications to authenticated;

revoke execute on function public.mark_notification_read(bigint) from public, anon;
grant execute on function public.mark_notification_read(bigint) to authenticated;
revoke execute on function public.mark_all_notifications_read() from public, anon;
grant execute on function public.mark_all_notifications_read() to authenticated;
revoke execute on function public.create_organization(text, text, text, text, text) from public, anon;
grant execute on function public.create_organization(text, text, text, text, text) to authenticated;
revoke execute on function public.update_organization(uuid, text, text, text, text, text) from public, anon;
grant execute on function public.update_organization(uuid, text, text, text, text, text) to authenticated;
revoke execute on function public.set_organization_status(uuid, text) from public, anon;
grant execute on function public.set_organization_status(uuid, text) to authenticated;
revoke execute on function public.assign_profile_to_organization(uuid, uuid) from public, anon;
grant execute on function public.assign_profile_to_organization(uuid, uuid) to authenticated;
revoke execute on function public.remove_profile_from_organization(uuid) from public, anon;
grant execute on function public.remove_profile_from_organization(uuid) to authenticated;

revoke execute on function public.create_notification_for_profile(uuid, text, text, text, bigint, bigint, text, boolean) from public, anon, authenticated;
revoke execute on function public.notify_admins(text, text, text, bigint, bigint, text, boolean) from public, anon, authenticated;
revoke execute on function public.notify_organization_members(uuid, text, text, text, bigint, bigint, text, boolean) from public, anon, authenticated;
revoke execute on function public.create_workflow_notifications() from public, anon, authenticated;

drop policy if exists "notifications_select_own" on public.notifications;
create policy "notifications_select_own"
on public.notifications
for select
to authenticated
using (recipient_user_id = auth.uid());
