-- Live IoT sensor ingestion infrastructure for ESP32/HC-SR04 prototype.
--
-- This migration is additive and non-destructive. It creates locked-down
-- sensor tables, public-safe/admin-safe views, and an admin-only RPC for
-- converting Warning/Critical sensor alerts into standard reports.
--
-- Device token setup pattern for a physical sensor:
-- 1. Generate a one-time token outside the database:
--    openssl rand -hex 32
-- 2. Store only the hash:
--    insert into public.sensor_devices (
--      sensor_id,
--      sensor_name,
--      sensor_type,
--      issue_type,
--      location_name,
--      latitude,
--      longitude,
--      risk_direction,
--      token_hash,
--      token_last_four
--    )
--    values (
--      'DRAIN-KIB-001',
--      'Kibera Soweto East Drainage Sensor',
--      'Drainage Water Level',
--      'Flooding / Stagnant Water',
--      'Kibera Soweto East',
--      -1.3133,
--      36.7870,
--      'lower_is_risk',
--      encode(extensions.digest('mkc-sensor-token-v1:' || '<DEVICE_TOKEN>', 'sha256'), 'hex'),
--      right('<DEVICE_TOKEN>', 4)
--    );
-- 3. Put only <DEVICE_TOKEN> on the ESP32, never a Supabase service-role key.

create extension if not exists pgcrypto;

create table if not exists public.sensor_devices (
  id uuid primary key default gen_random_uuid(),
  sensor_id text not null unique,
  sensor_name text not null,
  sensor_type text not null,
  issue_type text not null default 'Other Utility Risk',
  location_name text not null,
  latitude double precision,
  longitude double precision,
  risk_direction text not null default 'lower_is_risk',
  status text not null default 'Active',
  token_hash text not null unique,
  token_last_four text,
  last_seen_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.sensor_devices add column if not exists sensor_id text;
alter table public.sensor_devices add column if not exists sensor_name text;
alter table public.sensor_devices add column if not exists sensor_type text;
alter table public.sensor_devices add column if not exists issue_type text;
alter table public.sensor_devices add column if not exists location_name text;
alter table public.sensor_devices add column if not exists latitude double precision;
alter table public.sensor_devices add column if not exists longitude double precision;
alter table public.sensor_devices add column if not exists risk_direction text;
alter table public.sensor_devices add column if not exists status text;
alter table public.sensor_devices add column if not exists token_hash text;
alter table public.sensor_devices add column if not exists token_last_four text;
alter table public.sensor_devices add column if not exists last_seen_at timestamptz;
alter table public.sensor_devices add column if not exists created_at timestamptz;
alter table public.sensor_devices add column if not exists updated_at timestamptz;

create table if not exists public.sensor_alerts (
  id bigint generated by default as identity primary key,
  sensor_device_id uuid references public.sensor_devices(id) on delete restrict,
  sensor_id text not null,
  sensor_name text not null,
  sensor_type text not null,
  location_name text not null,
  latitude double precision,
  longitude double precision,
  reading_value numeric not null,
  reading_unit text not null default 'cm',
  threshold_value numeric,
  risk_level text not null,
  issue_type text not null,
  alert_status text not null default 'New',
  explanation text not null default '',
  measured_at timestamptz,
  received_at timestamptz not null default now(),
  converted_report_id bigint,
  converted_tracking_code text,
  converted_at timestamptz
);

alter table public.sensor_alerts add column if not exists sensor_device_id uuid;
alter table public.sensor_alerts add column if not exists sensor_id text;
alter table public.sensor_alerts add column if not exists sensor_name text;
alter table public.sensor_alerts add column if not exists sensor_type text;
alter table public.sensor_alerts add column if not exists location_name text;
alter table public.sensor_alerts add column if not exists latitude double precision;
alter table public.sensor_alerts add column if not exists longitude double precision;
alter table public.sensor_alerts add column if not exists reading_value numeric;
alter table public.sensor_alerts add column if not exists reading_unit text;
alter table public.sensor_alerts add column if not exists threshold_value numeric;
alter table public.sensor_alerts add column if not exists risk_level text;
alter table public.sensor_alerts add column if not exists issue_type text;
alter table public.sensor_alerts add column if not exists alert_status text;
alter table public.sensor_alerts add column if not exists explanation text;
alter table public.sensor_alerts add column if not exists measured_at timestamptz;
alter table public.sensor_alerts add column if not exists received_at timestamptz;
alter table public.sensor_alerts add column if not exists converted_report_id bigint;
alter table public.sensor_alerts add column if not exists converted_tracking_code text;
alter table public.sensor_alerts add column if not exists converted_at timestamptz;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'sensor_devices_status_check'
      and conrelid = 'public.sensor_devices'::regclass
  ) then
    alter table public.sensor_devices
      add constraint sensor_devices_status_check
      check (status in ('Active', 'Offline', 'Suspended')) not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'sensor_devices_risk_direction_check'
      and conrelid = 'public.sensor_devices'::regclass
  ) then
    alter table public.sensor_devices
      add constraint sensor_devices_risk_direction_check
      check (risk_direction in ('lower_is_risk', 'higher_is_risk')) not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'sensor_devices_issue_type_check'
      and conrelid = 'public.sensor_devices'::regclass
  ) then
    alter table public.sensor_devices
      add constraint sensor_devices_issue_type_check
      check (issue_type in (
        'Water Leak / Burst Pipe',
        'Blocked Drainage',
        'Sewage Overflow',
        'Unsafe Water Point',
        'Flooding / Stagnant Water',
        'Illegal Dumping',
        'Uncollected Waste',
        'Damaged Public Sanitation Facility',
        'Other Utility Risk'
      )) not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'sensor_devices_latitude_check'
      and conrelid = 'public.sensor_devices'::regclass
  ) then
    alter table public.sensor_devices
      add constraint sensor_devices_latitude_check
      check (latitude is null or (latitude >= -90 and latitude <= 90)) not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'sensor_devices_longitude_check'
      and conrelid = 'public.sensor_devices'::regclass
  ) then
    alter table public.sensor_devices
      add constraint sensor_devices_longitude_check
      check (longitude is null or (longitude >= -180 and longitude <= 180)) not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'sensor_alerts_risk_level_check'
      and conrelid = 'public.sensor_alerts'::regclass
  ) then
    alter table public.sensor_alerts
      add constraint sensor_alerts_risk_level_check
      check (risk_level in ('Normal', 'Warning', 'Critical')) not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'sensor_alerts_alert_status_check'
      and conrelid = 'public.sensor_alerts'::regclass
  ) then
    alter table public.sensor_alerts
      add constraint sensor_alerts_alert_status_check
      check (alert_status in ('New', 'Reviewed', 'Converted to Report')) not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'sensor_alerts_latitude_check'
      and conrelid = 'public.sensor_alerts'::regclass
  ) then
    alter table public.sensor_alerts
      add constraint sensor_alerts_latitude_check
      check (latitude is null or (latitude >= -90 and latitude <= 90)) not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'sensor_alerts_longitude_check'
      and conrelid = 'public.sensor_alerts'::regclass
  ) then
    alter table public.sensor_alerts
      add constraint sensor_alerts_longitude_check
      check (longitude is null or (longitude >= -180 and longitude <= 180)) not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'sensor_alerts_reading_value_check'
      and conrelid = 'public.sensor_alerts'::regclass
  ) then
    alter table public.sensor_alerts
      add constraint sensor_alerts_reading_value_check
      check (reading_value >= 0 and reading_value <= 100000) not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'sensor_alerts_threshold_value_check'
      and conrelid = 'public.sensor_alerts'::regclass
  ) then
    alter table public.sensor_alerts
      add constraint sensor_alerts_threshold_value_check
      check (threshold_value is null or (threshold_value >= 0 and threshold_value <= 100000)) not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'sensor_alerts_converted_report_fk'
      and conrelid = 'public.sensor_alerts'::regclass
  ) then
    alter table public.sensor_alerts
      add constraint sensor_alerts_converted_report_fk
      foreign key (converted_report_id) references public.reports(id) on delete set null not valid;
  end if;
end $$;

create unique index if not exists sensor_devices_sensor_id_idx
  on public.sensor_devices (sensor_id);

create index if not exists sensor_devices_status_idx
  on public.sensor_devices (status);

create index if not exists sensor_alerts_sensor_received_idx
  on public.sensor_alerts (sensor_id, received_at desc);

create index if not exists sensor_alerts_risk_status_idx
  on public.sensor_alerts (risk_level, alert_status, received_at desc);

create index if not exists sensor_alerts_converted_report_idx
  on public.sensor_alerts (converted_report_id)
  where converted_report_id is not null;

create or replace view public.admin_sensor_devices
with (security_barrier = true)
as
select
  id,
  sensor_id,
  sensor_name,
  sensor_type,
  issue_type,
  location_name,
  latitude,
  longitude,
  risk_direction,
  status,
  token_last_four,
  last_seen_at,
  created_at,
  updated_at
from public.sensor_devices
where public.is_admin();

create or replace view public.public_sensor_alerts
with (security_barrier = true)
as
select
  id,
  sensor_id,
  sensor_name,
  sensor_type,
  location_name,
  latitude,
  longitude,
  reading_value,
  reading_unit,
  threshold_value,
  risk_level,
  issue_type,
  alert_status,
  explanation,
  measured_at,
  received_at,
  converted_tracking_code
from public.sensor_alerts
where risk_level in ('Warning', 'Critical');

create or replace function public.convert_sensor_alert_to_report(
  p_alert_id bigint
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_alert public.sensor_alerts%rowtype;
  v_report_id bigint;
  v_tracking_code text;
  v_year text;
  v_urgency text;
  v_risk_score integer;
  v_risk_label text;
begin
  if auth.uid() is null then
    raise exception 'Authentication required' using errcode = '28000';
  end if;

  if not public.is_admin() then
    raise exception 'Admin role required' using errcode = '42501';
  end if;

  select * into v_alert
  from public.sensor_alerts
  where id = p_alert_id
  for update;

  if not found then
    raise exception 'Sensor alert not found' using errcode = 'P0002';
  end if;

  if v_alert.alert_status = 'Converted to Report' then
    raise exception 'Sensor alert has already been converted to a report' using errcode = 'P0001';
  end if;

  if v_alert.risk_level not in ('Warning', 'Critical') then
    raise exception 'Only Warning or Critical sensor alerts can be converted to reports' using errcode = 'P0001';
  end if;

  v_urgency := case
    when v_alert.risk_level = 'Critical' then 'Critical'
    else 'High'
  end;

  v_risk_label := case
    when v_alert.risk_level = 'Critical' then 'Critical'
    else 'High'
  end;

  v_risk_score := case
    when v_alert.risk_level = 'Critical' then 92
    else 76
  end;

  v_year := extract(year from now())::text;

  loop
    v_tracking_code := 'MKC-' || v_year || '-S' ||
      lpad((floor(random() * 900000) + 100000)::integer::text, 6, '0');
    exit when not exists (
      select 1 from public.reports
      where tracking_code = v_tracking_code
    );
  end loop;

  v_report_id := floor(extract(epoch from clock_timestamp()) * 1000)::bigint;

  while exists (
    select 1 from public.reports where id = v_report_id
  ) loop
    v_report_id := v_report_id + 1;
  end loop;

  insert into public.reports (
    id,
    tracking_code,
    issue_type,
    location_name,
    area,
    description,
    latitude,
    longitude,
    urgency,
    reporter_type,
    reporter_name,
    reporter_phone,
    reporter_email,
    is_anonymous,
    near_sensitive_area,
    risk_score,
    risk_label,
    status,
    created_at,
    photo_url
  )
  values (
    v_report_id,
    v_tracking_code,
    left(coalesce(nullif(v_alert.issue_type, ''), 'Flooding / Stagnant Water'), 120),
    left(coalesce(nullif(v_alert.location_name, ''), 'Sensor location'), 240),
    left(coalesce(nullif(v_alert.location_name, ''), 'Sensor location'), 240),
    left('[SENSOR] ' || coalesce(nullif(v_alert.explanation, ''), 'IoT sensor reading requires field verification.'), 2000),
    v_alert.latitude,
    v_alert.longitude,
    v_urgency,
    'IoT Sensor',
    '',
    '',
    '',
    true,
    'No',
    v_risk_score,
    v_risk_label,
    'Reported',
    now(),
    ''
  );

  insert into public.report_updates (
    report_id,
    status,
    note,
    updated_by,
    updated_by_name
  )
  values (
    v_report_id,
    'Reported',
    'Report created from sensor alert ' || v_alert.sensor_id || '.',
    auth.uid(),
    'Make Kenya Clean Sensor Ingestion'
  );

  update public.sensor_alerts
  set
    alert_status = 'Converted to Report',
    converted_report_id = v_report_id,
    converted_tracking_code = v_tracking_code,
    converted_at = now()
  where id = p_alert_id;

  return jsonb_build_object(
    'success', true,
    'alert_id', p_alert_id,
    'report_id', v_report_id,
    'tracking_code', v_tracking_code
  );
end;
$$;

alter table public.sensor_devices enable row level security;
alter table public.sensor_alerts enable row level security;

revoke all on public.sensor_devices from anon, authenticated;
revoke all on public.sensor_alerts from anon, authenticated;

grant select on public.sensor_alerts to authenticated;
grant select on public.admin_sensor_devices to authenticated;
grant select on public.public_sensor_alerts to anon, authenticated;

drop policy if exists "sensor_alerts_admin_select" on public.sensor_alerts;
create policy "sensor_alerts_admin_select"
on public.sensor_alerts
for select
to authenticated
using (public.is_admin());

revoke execute on function public.convert_sensor_alert_to_report(bigint) from public, anon;
grant execute on function public.convert_sensor_alert_to_report(bigint) to authenticated;

-- The ingestion Edge Function uses the service-role key server-side only. Grant
-- this helper to service_role so obvious sensor spam can reuse the existing
-- privacy-preserving rate-limit table without exposing it to browser clients.
grant execute on function public.assert_rate_limit(text, text, integer, integer) to service_role;
